add new 'Compare to' section under ESC in docs
pulumi/docs pull request #11934
Opened 2024-05-31 19:24 UTC by shughes26

### Proposed changes

Added new `Compare to` directory under ESC in docs, and page for ESC vs Vault

2024-05-31 22:00 UTC, aaronkao requested changes
Pushing through some changes here

2024-05-31 22:00 UTC, aaronkao commented on content/docs/esc/vs/_index.md
> +* [Hashicorp Terraform](/docs/concepts/vs/vault/)
```suggestion
* [HashiCorp Vault](/docs/esc/vs/vault/)
```

2024-05-31 23:22 UTC, arunkumar611 commented
We should change the get started here at the bottom of the page. It is talking about IaC:

<img width="1098" alt="image" src="https://github.com/pulumi/docs/assets/14963978/a4626919-39f4-47e8-85d3-144463ef767d">

2024-06-04 00:38 UTC, aaronkao commented on layouts/shortcodes/get-started-esc.html
> +                    <img class="h-10 mx-auto" src="/logos/tech/terraform.svg" alt="Terraform" />
This should be Vault and not Terraform

2024-08-14 21:16 UTC, aaronkao approved these changes

2024-08-14 21:37 UTC, merged