New bitbucket guide
pulumi/docs pull request #13032
Opened 2024-10-03 20:40 UTC by interurban

Adding a new guide to cover how to configure Bitbucket Pipelines with Pulumi

2024-10-03 23:34 UTC, automagic requested changes

2024-10-04 15:46 UTC, automagic commented on content/docs/iac/packages-and-automation/continuous-delivery/bitbucket.md
> +h1: Pulumi CI/CD & Bitbucket
Consider "Pulumi CI/CD with Bitbucket Pipelines".    Since we specify "Github Actions" instead of just "Github" in that guide.

2024-10-04 15:46 UTC, automagic commented on content/docs/iac/packages-and-automation/continuous-delivery/bitbucket.md
> +Once the `.bitbucket-pipelines.yml` is committed, each push to the repository will trigger the pipeline, automating the deployment of your infrastructure. You can monitor the pipeline status in the *
"each push or pull request to the main branch of the repository"

2025-01-08 19:42 UTC, thoward requested changes
I think this needs to merge w/ master before being approved. The left nav moved to "Using Pulumi" in this change: https://github.com/pulumi/docs/pull/13616 ... but this preview shows the old naming convention, and the URL changes here are also reflecting the old naming convention.

2025-01-09 22:30 UTC, closed without merging