Add Reference Google Cloud Resources Across Stacks Tutorial Content
pulumi/docs pull request #13347
Opened 2024-11-14 13:46 UTC by toriancrane

### Proposed changes

- Adds the content for the Google Cloud-specific stack references and outputs tutorials
- Updates the closing paragraph of the Azure stack ref tutorial to replace incorrect AWS references with Azure references.

2024-11-19 20:52 UTC, dirien approved these changes
LGTM! But I did not run all the code to see if it's working on runtime.

2024-12-03 08:52 UTC, thoward requested changes
LGTM (except the asset bundles as noted)

2024-12-03 08:52 UTC, thoward commented on assets/css/bundle.css
See comment on other recent PR: https://github.com/pulumi/docs/pull/13390#discussion_r1867266943

Please remove the commits for these rendered asset files from this branch (not the files).

2024-12-03 08:52 UTC, thoward commented on content/tutorials/stack-outputs-refs-azure/index.md
> +In this tutorial, you created an Azure Blob Storage and Container resource. You also referenced the documentation to create a Blob object that would upload a file to the container. You exported resou
Nice catch!

2024-12-03 10:44 UTC, thoward approved these changes

2024-12-03 10:52 UTC, merged