Update Venafi Setup Guide
pulumi/docs pull request #4557
Opened 2020-11-10 18:35 UTC by stack72

2020-11-11 15:37 UTC, isaac-pulumi commented on content/docs/intro/cloud-providers/venafi/setup.md
>  2. Set them using configuration, if you prefer that they be stored alongside your Pulumi stack for easy multi-user access:
```suggestion
2. Using configuration, if you prefer storing authorization tokens alongside your Pulumi stack for easy multi-user access:
```

2020-11-11 15:38 UTC, isaac-pulumi commented on content/docs/intro/cloud-providers/venafi/setup.md
> +1. Set the environment variables `VENAFI_URL`, `VENAFI_TOKEN` and `VENAFI_ZONE`:
```suggestion
1. By setting the environment variables `VENAFI_URL`, `VENAFI_TOKEN` and `VENAFI_ZONE`:
```

2020-11-11 15:40 UTC, isaac-pulumi commented on content/docs/intro/cloud-providers/venafi/setup.md
> +To generate an access token for TPP Admin, then we can make a `POST` request to the TPP Admin URL. An example would be as
```suggestion
To generate an access token for TPP Admin, make a `POST` request to the TPP Admin URL. An example would be as
```

2020-11-11 15:41 UTC, isaac-pulumi requested changes
Suggested some changes for clarity.

2020-11-11 19:20 UTC, stack72 commented
@isaac-pulumi made those changes - please +1 if you are happy with them!

2020-11-12 14:49 UTC, isaac-pulumi commented on content/docs/intro/cloud-providers/venafi/setup.md
> +1. By setting the environment variables `VENAFI_URL`, `VENAFI_TOKEN` and `VENAFI_ZONE`:
```suggestion
1. Setting the environment variables `VENAFI_URL`, `VENAFI_TOKEN` and `VENAFI_ZONE`:
```

2020-11-12 14:50 UTC, isaac-pulumi approved these changes
changes look good

2020-11-12 15:52 UTC, merged