s/isMini[kK]ube/useLoadBalancer/g
pulumi/docs pull request #4760
Opened 2020-12-09 05:24 UTC by pcuci

Update the polyglot sample code to match the surrounding explanatory docs

Since MicroK8s, like minikube, can also be setup without a load balancer, the more explicit and generic `useLoadBalancer` config flag seems more portable

re: https://www.pulumi.com/docs/tutorials/kubernetes/guestbook/ as of 2020-12-09

2020-12-10 07:42 UTC, leezen commented
Thanks for the suggestion here. I think this makes sense. A couple things: I'd love for someone else to also take a look, so tagging in @viveklak to see what he thinks about this change. Separately, the changes here only affect the text of the tutorial and the underlying examples should be changed as well. Do you mind opening a PR against https://github.com/pulumi/examples with the changes for the actual examples to reflect what you're doing here as well?

2020-12-10 17:55 UTC, viveklak requested changes

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
>  // Minikube does not implement services of type `LoadBalancer`; require the user to specify if we're
Nit - the comment here can be reworded to remove mention of minikube as well.

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
> +        type: useLoadBalancer ? "ClusterIP" : "LoadBalancer",
You want to flip the branches here right? i.e. use `LoadBalancer` when `useLoadBalancer` and `ClusterIP` otherwise.

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
> +if (useLoadBalancer) {
See above comment about flipping branch.

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
>  # Minikube does not implement services of type `LoadBalancer`; require the user to specify if we're
Exclude reference to minikube

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
> +        "type": "ClusterIP" if useLoadBalancer else "LoadBalancer",
Flip branch

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
> +if useLoadBalancer:
Flip branches

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
>          // Minikube does not implement services of type `LoadBalancer`; require the user to specify if we're
Exclude reference to minikube

2020-12-10 17:55 UTC, viveklak commented on content/docs/tutorials/kubernetes/guestbook.md
> +        if useLoadBalancer {
Flip branch - i.e. `LoadBalancer` when `useLoadBalancer` is true and `ClusterIP` otherwise.

2020-12-11 02:52 UTC, pcuci commented
I think I got all of them @viveklak @leezen—thx!

2021-04-07 16:12 UTC, cnunciato commented
@pcuci We've moved this content to a new repository that's now located at https://github.com/pulumi/pulumi-hugo. Would you mind resubmitting it there? Thanks!

2021-07-28 21:12 UTC, leezen commented
Closing stale PR -- and reopening in `pulumi-hugo`: https://github.com/pulumi/pulumi-hugo/pull/456

2021-07-28 21:12 UTC, closed without merging