Refresh old EKS blog post
pulumi/docs pull request #4965
Opened 2021-01-13 23:32 UTC by lblackstone

TODO

- [ ] Update content for .NET and Go

2021-01-15 00:29 UTC, spara requested changes
Some minor changes. This is pretty cool, do you think it would work with EKS Anywhere?

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
> +no easy task. AWS now offers EKS to ease a lot of that burden -- but
```suggestion
not easy. AWS now offers EKS to reduce that burden -- but
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
> +code can help! We can now provision an entire EKS cluster with a
```suggestion
code SDKs can help! We can provision an entire EKS cluster with a
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
> +the `pulumi` CLI we'll be using below. If you don't already
```suggestion
the `pulumi` CLI we'll use below. If you don't
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
> +Using this template will walk you through configuring a few settings
```suggestion
This template will walk you through configuring a few settings
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
> +such as the region you'd like to deploy into, the instance type, and
```suggestion
such as the region to deploy, the instance type, and
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
>  the cluster need access to an Amazon S3 bucket, simply create a new
```suggestion
the cluster need access to an Amazon S3 bucket, create a new
```

2021-01-15 00:29 UTC, spara commented on content/blog/easily-create-and-manage-aws-eks-kubernetes-clusters-with-pulumi/index.md
>  Or, to install some Kubernetes applications automatically into the
```suggestion
Or, to install Kubernetes applications automatically into the
```

2021-01-15 00:34 UTC, lblackstone commented
> This is pretty cool, do you think it would work with EKS Anywhere?

Seems like it should, in principle, but I'm only vaguely familiar with that product line.

2021-01-15 15:42 UTC, spara commented
> > This is pretty cool, do you think it would work with EKS Anywhere?
> 
> Seems like it should, in principle, but I'm only vaguely familiar with that product line.

I took another look at it again, and it seems like there's a lot of new information. I think we should republish it next week as an update to the original post dated for next Thursday,  What do you think?

2021-01-15 16:46 UTC, lblackstone commented
> I think we should republish it next week as an update to the original post dated for next Thursday, What do you think?

Yes, that sounds good. I'll make a few more updates early next week and then it should be good to go.

2021-01-15 16:50 UTC, spara commented
> > This is pretty cool, do you think it would work with EKS Anywhere?
> 
> Seems like it should, in principle, but I'm only vaguely familiar with that product line.



> > I think we should republish it next week as an update to the original post dated for next Thursday, What do you think?
> 
> Yes, that sounds good. I'll make a few more updates early next week and then it should be good to go.

Great! 👍

2021-01-15 17:19 UTC, spara approved these changes

2021-01-19 22:50 UTC, lblackstone commented
@spara I updated the publish date, so I think this should be ready to merge on Thursday.

2021-01-28 16:25 UTC, merged