[blog] Automation Your Infrastructure with Automation API and C#
pulumi/docs pull request #5380
Opened 2021-03-02 14:41 UTC by orionstudt

2021-03-03 19:20 UTC, leezen commented on content/blog/automation-api-dotnet/index.md
> +- joshua-studt
FYI: you'll want to add a `.toml` file to `data/team/team` for this to render correctly.

2021-03-03 19:33 UTC, spara commented
Josh, I manage the blog, let me know if you need any assistance, always happy to help out.

sophia

2021-03-03 20:00 UTC, orionstudt commented
Hi @spara! I'd love an assist. I can put some more energy into this when I get off work today buy when I started this I was looking primarily at the [python announcement post](https://www.pulumi.com/blog/automation-api-python/) as an example. That post doesn't really talk about python implementation specifics at all - the only thing python is the code samples. It seems to mostly be a post that describes the Automation API itself, which made it a difficult example to follow since I didn't want to just copy your homework!

So, how much of this post do we want to be reiterating what the Automation API is and what it does? I was just going to get right into dotnet examples after linking to a more thorough post describing the feature, but that will make this post significantly more brief.

2021-03-03 20:39 UTC, spara commented
Go ahead and write up the dotnet examples part and I can throw in a paragraph about Auto API and some fresh new use cases like our new Github Actions provider. I can look at your examples and reference those as well.

2021-03-04 19:11 UTC, spara requested changes
Made a few changes, would like @leezen and @infin8x to also review

2021-03-04 19:11 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +meta_desc: "tbd"
```suggestion
meta_desc: "C# developers can programmatically build infrastructure (with out a CLI) using the Pulumi Automation API package. "
```

2021-03-04 19:11 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +See the full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet).
```suggestion
See full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet).
```

2021-03-04 22:04 UTC, leezen approved these changes
Looks great! I just had a couple small things I didn't have a huge opinion on and defer to @orionstudt

2021-03-04 22:09 UTC, orionstudt commented on content/blog/automation-api-dotnet/index.md
> +The `Pulumi.Automation` [NuGet package](https://github.com/pulumi/pulumi/tree/master/sdk/dotnet/Pulumi.Automation) exposes a `LocalWorkspace` for  creating and managing Pulumi [Stacks]({{< relref "/d
Yea that sounds better - done

2021-03-04 22:12 UTC, orionstudt commented
Should be good now I think then!

2021-03-04 23:14 UTC, spara approved these changes
Fixed shortcode error, removed extraneous line, set publish date, and added call to action.

2021-03-04 23:14 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +{{% /notes %}
```suggestion
{{% /notes %}}

```

2021-03-04 23:14 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +date: tbd
```suggestion
date: 2021-03-08
```

2021-03-04 23:14 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +
```suggestion
```

2021-03-04 23:14 UTC, spara commented on content/blog/automation-api-dotnet/index.md
> +See full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet).
```suggestion
See full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet). Let us know if you're using Automation API on [Twitter](https://twitter.com/PulumiCorp) or in [Pulumi Comunity Slack](https://slack.pulumi.com/).
```

2021-03-05 21:28 UTC, infin8x approved these changes
This looks great - thanks @orionstudt for contributing! A few suggestions but otherwise LGTM.

2021-03-05 21:28 UTC, infin8x commented on content/blog/automation-api-dotnet/index.md
> +Currently available in public preview, Pulumi's Automation API lets you to programmatically call upon the Pulumi engine to provision your infrastructure. Today, we are excited to announce C# support
```suggestion
Currently available in public preview, Pulumi's Automation API enables you to provision your infrastructure programmatically using the Pulumi engine. Today, we are excited to announce C# support for Automation API, enabling .NET developers to automate infrastructure deployments, create complex orchestration workflows, build custom ops tooling, and build cloud frameworks. Read more about the Automation API [here]({{< relref "/blog/automation-api" >}}).
```

2021-03-05 21:28 UTC, infin8x commented on content/blog/automation-api-dotnet/index.md
> +See full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet). Let us know if you're using Automation API on [Twitter](https://twitter.com/PulumiCorp) o
```suggestion
See full Automation API examples in [C#](https://github.com/pulumi/automation-api-examples/tree/main/dotnet). Let us know if you're using Automation API on [Twitter](https://twitter.com/PulumiCorp) or in our [Community Slack](https://slack.pulumi.com/).
```

2021-03-08 16:30 UTC, merged