Added supported languages and example
pulumi/docs pull request #9664
Opened 2023-08-11 11:03 UTC by toriancrane

### Proposed changes

Added a table to demonstrate the supported languages for source and destination. Also added a simple yaml to java example. This will help to make it clearer to readers that YAML, Terraform, and PCL are currently the only supported source languages, and all of Pulumi's supported languages are available as a target language. The simple example will provide an easy to use reference for how to use this command.

### Related issues (optional)

Fixes [Issue 12720](https://github.com/pulumi/pulumi/issues/12720)

2023-08-11 15:37 UTC, scottslowe requested changes
Useful addition, thanks! Just one comment regarding whether PCL needs to be included/exposed here.

2023-08-11 15:37 UTC, scottslowe commented on content/docs/cli/commands/pulumi_convert.md
> +### Supported Languages
I could be wrong, but I don't think we need to expose PCL here. PCL isn't documented (I believe that's intentional) as it is an internal representation that Pulumi uses.

2023-08-11 16:30 UTC, cnunciato commented
@toriancrane These docs are generated, so any changes we make to them directly will be overwritten on the next CLI release. If we want to augment them with additional content, we'll probably need to do so with something like a shortcode or change to the layout somehow.

2023-08-21 18:42 UTC, cnunciato commented
@scottslowe Yeah, we chatted about this a bit this morning at triage. Since we don't yet have a good way to inject content into these generated pages, I thought we might be able to address the core issue (conveying which languages are supported) in the CLI help text itself somehow, e.g., here: https://github.com/pulumi/pulumi/blob/2016359133bb5c7d3b213c7f6b9db212cf35e283/pkg/cmd/pulumi/convert.go#L62-L77

.. and/or on the `from` or `language` options themselves: https://github.com/pulumi/pulumi/blob/2016359133bb5c7d3b213c7f6b9db212cf35e283/pkg/cmd/pulumi/convert.go#L79-L88

Not perfect of course, but perhaps a good interim solution.

2023-08-23 18:27 UTC, cnunciato reviewed
Do y'all think we should close this, given it can't really merge as-is?

2023-08-23 19:52 UTC, scottslowe commented
> Do y'all think we should close this, given it can't really merge as-is?

Yeah, that's probably the right thing to do.

2023-09-07 09:17 UTC, closed without merging